### ISSUE TITLE
Missing images in Loris 2.1.0's cache

### ISSUE THREAD

**Issue by deutsches-museum-digital** [loris-imageserver/loris#289]
After upgrading from 2.0.0 to 2.1.0, and a purge of Loris2's cache, derivatives of certain images are suddenly missing. They were properly delivered under 2.0.0.

When investigating this issue, I noticed something that appeared quite strange to me. One of the missing images is a derivative having a height of 144 pixels (and an implicit width of 192 pixels) of an image file named 1965T19_0001.jpg. When looking at Loris2's cache, I see that this is a link to another derivative which is supposed to have a width of 203 pixels:

```
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T19_0001/full/,144/0/
total 8
drwxr-xr-x 2 loris loris 4096 Apr  7 15:41 .
drwxr-xr-x 3 loris loris 4096 Apr  7 15:41 ..
lrwxrwxrwx 1 loris loris   55 Apr  7 15:41 default.jpg -> /data/cache/loris2/1965T19_0001/full/203,/0/default.jpg
```

But this file has never been explicitly requested and is unavailable:

```
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T19_0001/full/203,/0/default.jpg
ls: cannot access 1965T19_0001/full/203,/0/default.jpg: No such file or directory
```

If investigating a file that _is_ being delivered (having a height of 144 pixels as well and an implicit width of 125 pixels), it looks much more reasonable:

```
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T29_0001/full/,144/0/
total 8
drwxr-xr-x 2 loris loris 4096 Apr  7 17:21 .
drwxr-xr-x 3 loris loris 4096 Apr  7 17:21 ..
lrwxrwxrwx 1 loris loris   55 Apr  7 17:21 default.jpg -> /data/cache/loris2/1965T29_0001/full/125,/0/default.jpg
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T29_0001/full/125,/0/default.jpg
-rw-r--r-- 1 loris loris 5520 Apr  7 17:21 1965T29_0001/full/125,/0/default.jpg
```

But then again, bigger derivatives of the first file having widths of 1200 and 519 pixels are missing as well despite the fact that they were explicitly requested:

```
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T20_0001/full/1200,/0/default.jpg
ls: cannot access 1965T20_0001/full/1200,/0/default.jpg: No such file or directory
schweizer@dmdigi002:/data/cache/loris2$ ls -la 1965T20_0001/full/519,/0/default.jpg
ls: cannot access 1965T20_0001/full/519,/0/default.jpg: No such file or directory
```

The respective error messages in the Apache logs when requesting these two files are as follows:

```
[Mon Apr 10 11:39:44.068919 2017] [:error] [pid 24793:tid 140421360899840] /usr/local/lib/python2.7/dist-packages/PIL/Image.py:2221: DecompressionBombWarning: Image size (139201551 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
[Mon Apr 10 11:39:44.068960 2017] [:error] [pid 24793:tid 140421360899840]   DecompressionBombWarning)
[Mon Apr 10 11:39:46.119506 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329] mod_wsgi (pid=24794): Exception occurred processing WSGI script '/var/www/loris2/loris2.wsgi'.
[Mon Apr 10 11:39:46.119557 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329] Traceback (most recent call last):
[Mon Apr 10 11:39:46.119573 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 387, in __call__
[Mon Apr 10 11:39:46.119596 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]     return self.wsgi_app(environ, start_response)
[Mon Apr 10 11:39:46.119617 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 338, in wsgi_app
[Mon Apr 10 11:39:46.119631 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]     response = self.route(request)
[Mon Apr 10 11:39:46.119640 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 381, in route
[Mon Apr 10 11:39:46.119650 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]     return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
[Mon Apr 10 11:39:46.119658 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 593, in get_img
[Mon Apr 10 11:39:46.119668 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]     r.last_modified = datetime.utcfromtimestamp(path.getctime(fp))
[Mon Apr 10 11:39:46.119676 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]   File "/usr/lib/python2.7/genericpath.py", line 64, in getctime
[Mon Apr 10 11:39:46.119687 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329]     return os.stat(filename).st_ctime
[Mon Apr 10 11:39:46.119706 2017] [:error] [pid 24794:tid 140421344114432] [remote 192.168.10.1:41329] OSError: [Errno 2] No such file or directory: '/data/cache/loris2/1965T20_0001/full/1200,/0/default.jpg'
[Mon Apr 10 11:39:48.652365 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257] mod_wsgi (pid=24796): Exception occurred processing WSGI script '/var/www/loris2/loris2.wsgi'.
[Mon Apr 10 11:39:48.652429 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257] Traceback (most recent call last):
[Mon Apr 10 11:39:48.652445 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 387, in __call__
[Mon Apr 10 11:39:48.652470 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]     return self.wsgi_app(environ, start_response)
[Mon Apr 10 11:39:48.652479 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 338, in wsgi_app
[Mon Apr 10 11:39:48.652492 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]     response = self.route(request)
[Mon Apr 10 11:39:48.652499 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 381, in route
[Mon Apr 10 11:39:48.652509 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]     return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
[Mon Apr 10 11:39:48.652516 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]   File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 593, in get_img
[Mon Apr 10 11:39:48.652529 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]     r.last_modified = datetime.utcfromtimestamp(path.getctime(fp))
[Mon Apr 10 11:39:48.652540 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]   File "/usr/lib/python2.7/genericpath.py", line 64, in getctime
[Mon Apr 10 11:39:48.652554 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257]     return os.stat(filename).st_ctime
[Mon Apr 10 11:39:48.652573 2017] [:error] [pid 24796:tid 140421344114432] [remote 192.168.10.1:38257] OSError: [Errno 2] No such file or directory: '/data/cache/loris2/1965T20_0001/full/519,/0/default.jpg'
```

I wonder if the "DecompressionBombWarning" in the first line of it has got to do with the issue?

**Comment by minusdavid** [comment]
Oh this is interesting. I've started seeing DecompressionBombWarning errors as well.

**Comment by bcail** [comment]
Here's a Pillow issue about it: https://github.com/python-pillow/Pillow/issues/515. Looks like we need to let the user configure the Pillow Image.MAX_IMAGE_PIXELS setting.

**Comment by minusdavid** [comment]
> Here's a Pillow issue about it: [python-pillow/Pillow#515](https://github.com/python-pillow/Pillow/issues/515). Looks like we need to let the user configure the Pillow Image.MAX_IMAGE_PIXELS setting.

Sounds good to me!
