### ISSUE TITLE
os.stat() failure on OSX causes 500 errors

### ISSUE THREAD

**Issue by thatbudakguy** [loris-imageserver/loris#290]
**System**: OSX 10.11.6
**Version**: `lorisimageserver/loris` docker image
**Issue**: Almost all requests to Loris are failing with 500 errors. I have mounted a single image into my container at `/usr/local/share/images` using the `volumes` stanza in `docker-compose`. Issue seems to be related to [this stackoverflow question](http://stackoverflow.com/questions/23963397/how-do-i-reliably-retrieve-a-files-last-modified-time-on-os-x) about differences in `stat` and the value of `st_mtime`.
**Output**:
```python
(werkzeug) [ERROR]: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/opt/loris/loris/webapp.py", line 360, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/loris/loris/webapp.py", line 254, in wsgi_app
    response = self.route(request)
  File "/opt/loris/loris/webapp.py", line 290, in route
    return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
  File "/opt/loris/loris/webapp.py", line 488, in get_img
    img_last_mod = datetime.utcfromtimestamp(path.getmtime(fp))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
TypeError: coercing to Unicode: need string or buffer, tuple found
```

**Comment by thatbudakguy** [comment]
The problem doesn't exist when the containers are first booted up, but if I refresh the page containing my Mirador viewer, suddenly it will appear, and all following requests to Loris will fail.

**Comment by thatbudakguy** [comment]
Building a new container with the images baked in didn't resolve the problem - images were rendered after the first `docker-compose build` but now the issue has appeared again. Not sure what to do at this point.

**Comment by thatbudakguy** [comment]
Seem to have resolved this by bumping the loris version in the Dockerfile to 2.1.0 and rebuilding, so it may not be an issue anymore. Will file a PR.
