### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Kevin-Darty** [loris-imageserver/loris#304]
Hi,

I followed the installation instructions but I have the following issue when executing setup.py:
`kevin@data:/home/data/loris-development$ sudo ./setup.py install --loris-owner data --loris-group data`
The installation starts and then an error is raised:
```
Installed /usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg
Processing dependencies for Loris==2.0.0
Finished processing dependencies for Loris==2.0.0
Traceback (most recent call last):
  File "./setup.py", line 242, in <module>
    install_requires=install_requires
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 126, in run
    self.__update_and_deploy_config()
  File "./setup.py", line 204, in __update_and_deploy_config
    config = ConfigObj(config_file_src, unrepr=True, interpolation=False)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 101.
```

Any idea from where this error comes from ?
Thanks in advance

Some other informations:
Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
```
python --version
Python 2.7.9
```
```
kdu_compress -v
This is Kakadu's "kdu_compress" application.
    Compiled against the Kakadu core system, version v7.9
    Current core system version is v7.9
```

```
sudo pip install --upgrade Pillow
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow)
Cleaning up...
```

```
sudo pip show werkzeug pillow configobj ordereddict requests mock responses
---
Name: Werkzeug
Version: 0.12.2
Location: /usr/local/lib/python2.7/dist-packages/Werkzeug-0.12.2-py2.7.egg
Requires:
---
Name: Pillow
Version: 4.1.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: olefile
---
Name: configobj
Version: 5.0.6
Location: /usr/local/lib/python2.7/dist-packages
Requires: six
---
Name: requests
Version: 2.4.3
Location: /usr/lib/python2.7/dist-packages
Requires:
---
Name: mock
Version: 2.0.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, funcsigs, pbr
---
Name: responses
Version: 0.5.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: cookies, six, mock, requests
```

**Comment by bcail** [comment]
@niwizard 
`configobj.ConfigObjError: Parsing failed with several errors.`
Looks like an error parsing loris2.conf - have you modified that file locally?

**Comment by Kevin-Darty** [comment]
Yes I modified it.

I added a `[resolver]` but didn't see that one was already there.
Commenting the original [resolver] and the two following configuration lines solved the problem.

Thanks !

**Comment by bcail** [comment]
@niwizard is there still an issue, or can this be closed?

**Comment by Kevin-Darty** [comment]
This specific issue is resolved but I'm having other problems that might be linked to my server (that's why I close and reopened this thread).
I will open another thread if these other problems are directly linked to Loris and if I do not resolve them by myself.

Thanks again
