### ISSUE TITLE
Documentation around logging parameters is potentially inaccurate

### ISSUE THREAD

**Issue by alexwlchan** [loris-imageserver/loris#337]
It’s 10:20pm local time, so I don’t have time to put up a proper patch tonight. Briefly: Loris 2.1.0, Python 2.7 running on Ubuntu 14.04. Here’s my logging config:

```
[logging]
log_to = 'file'    # 'console'|'file'
log_level = 'INFO'  # 'DEBUG'|'INFO'|'WARNING'|'ERROR'|'CRITICAL'
```

The configuration docs say:

> The rest only matter if `log_to=file`: […]
>
> * `format`. Format of the log entries. See Python LogRecord attributes for options.

But I’m getting the following error when I try to start Loris:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 117, in __configure_logging
    config_file_path='/opt/loris/etc/loris2.conf')
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 74, in create_app
    logger = __configure_logging(config['logging'])
  File "/var/www/loris2/loris2.wsgi", line 8, in <module>
    formatter = logging.Formatter(fmt=config['format'])
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 570, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'format'
```

I don’t think `format` is only applicable when logging to file.

**Comment by alexwlchan** [comment]
I can’t read, can I? It’s still logging to file, I thought I’d changed it to log to console. 10pm is the wrong time to be debugging!
