### ISSUE TITLE
Occasional 'NoneType object is not callable' errors in log

### ISSUE THREAD

**Issue by alexwlchan** [loris-imageserver/loris#341]
We've seen this error crop up several times in our logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 708, in close
    callback()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 1113, in close
    func()
TypeError: 'NoneType' object is not callable
```

while running the latest version from development. I wasn’t sure if it was a UWSGI config error, or some other bug on my side. (Unsurprisingly, Googling for that error doesn’t turn up anything useful.)\

I’ve tracked down the bug, patch incoming shortly.

**Comment by alexwlchan** [comment]
The TypeError is being emitted from this method in Werkzeug:

```python
def close(self):
    """Close the wrapped response if possible.  You can also use the object
    in a with statement which will automatically close it.
    """
    if hasattr(self.response, 'close'):
        self.response.close()
    for func in self._on_close:
        func()
```

Digging into where the `_on_close` attribute is being set by Loris, I found this line in `webapp.py`:

```
r.call_on_close(unlink(fp))
```

where `r` is an instance of `LorisResponse`, in turn a subclass of `werkzeug.wrappers.BaseResponse`. That method [takes a callback](http://werkzeug.pocoo.org/docs/0.12/wrappers/#werkzeug.wrappers.BaseResponse.call_on_close) that gets stored in `self._on_close`, where here the callback is called immediately, and the result is accessed later.

Fix is to replace this with:

```
r.call_on_close(lambda: unlink(fp))
```
