### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by minusdavid** [loris-imageserver/loris#404]
In dependencies.md, it says that you only need to install configobj, if you're not going to run setup.py. 

However, I got the following when I ran "./setup.py install --record files.txt":

Installed /usr/local/lib/python2.7/dist-packages/chardet-3.0.4-py2.7.egg
Finished processing dependencies for Loris==2.2.0
writing list of installed files to 'files.txt'
Traceback (most recent call last):
  File "./setup.py", line 238, in <module>
    install_requires=install_requires
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 122, in run
    self.__update_and_deploy_config()
  File "./setup.py", line 196, in __update_and_deploy_config
    from configobj import ConfigObj # can do now that we've installed it!
ImportError: No module named configobj

I tried installing configobj with pip but it said it was already installed... and then I re-ran setup.py and it was all seemingly fine.

Something weird going on there though...

**Comment by alexwlchan** [comment]
Yeah, that's odd. Thanks for the report!

Which commit/release were you trying to install from?

(Also, I'm amused that a "Module not found" error is issue 404…)

**Comment by minusdavid** [comment]
Apologies for the delay. 

I believe that would be for release 2.2.0. 

(Hehe. That is amusing!)

**Comment by heacu** [comment]
just to say, this happened exactly as described above by @minusdavid to me as well, installing from latest commit https://github.com/loris-imageserver/loris/commit/e8881f6fefc5eb7ceb69dc311003c00127c491c1
