### ISSUE TITLE
configobj.InterpolationLoopError: interpolation loop detected in value "PATH".

### ISSUE THREAD

**Issue by lguariento** [loris-imageserver/loris#457]
I want to deploy Loris with Nginx and uWSGI. This is my loris.wsgi:

```
#!/root/python_ve/lib/python3.7/site-packages python
#-*- coding: utf-8 -*-

import sys
from os import path

project_dp = path.dirname(path.dirname(path.realpath(__file__)))

sys.path.append(project_dp)

from loris.webapp import create_app
application = create_app(debug=False, config_file_path='/root/python_ve/loris/etc/loris2.conf')
```

And this is the error I get:

```
Traceback (most recent call last):
  File "/var/www/loris/loris.wsgi", line 16, in <module>
    application = create_app(debug=False, config_file_path='python_ve/loris/etc/loris2.conf')
  File "./loris/webapp.py", line 100, in create_app
    return Loris(config)
  File "./loris/webapp.py", line 326, in __init__
    for key in self.app_configs for sub_key in self.app_configs[key]]
  File "./loris/webapp.py", line 326, in <listcomp>
    for key in self.app_configs for sub_key in self.app_configs[key]]
  File "python_ve/lib/python3.7/site-packages/configobj.py", line 557, in __getitem__
    return self._interpolate(key, val)
  File "python_ve/lib/python3.7/site-packages/configobj.py", line 549, in _interpolate
    return engine.interpolate(key, value)
  File "python_ve/lib/python3.7/site-packages/configobj.py", line 352, in interpolate
    value = recursive_interpolate(key, value, self.section, {})
  File "python_ve/lib/python3.7/site-packages/configobj.py", line 336, in recursive_interpolate
    replacement = recursive_interpolate(k, v, s, backtrail)
  File "python_ve/lib/python3.7/site-packages/configobj.py", line 321, in recursive_interpolate
    raise InterpolationLoopError(key)
configobj.InterpolationLoopError: interpolation loop detected in value "PATH".
```

What am I missing? Thanks.

**Comment by bcail** [comment]
@lguariento see https://configobj.readthedocs.io/en/latest/configobj.html#string-interpolation - it talks about the InterpolationLoopError. Check the value of your PATH environment variable, and try printing out app_configs on line 323 of loris/webapp.py.

**Comment by lguariento** [comment]
Sorry for the stupid question: how do I do that?

`self.logger.debug('Configs are %s', app_configs)` doesn't seem to print out anything.

**Comment by bcail** [comment]
You could try using a print() statement, and see if you can view the output that way.

**Comment by lguariento** [comment]
That was the first thing I did:

```
        self.app_configs = app_configs
        self.logger = configure_logging(app_configs['logging'])
        print('Configs are %s', app_configs)
```

doesn't seem to do anything at all :/

**Comment by bcail** [comment]
you're using docker, right? That may be a docker question. But you could also try going back to the self.logger statement, but use self.logger.error() instead of debug. It could be that debug logger output is suppressed.

**Comment by lguariento** [comment]
This is my `echo $PATH` by the way:

```
/root/.nvm/versions/node/v10.11.0/bin:/opt/maven/bin:$PATH:$PATH:$JAVA_HOME/bin:/usr/bin:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/root/bin:/usr/local/bin:/usr/sbin
```

**Comment by lguariento** [comment]
No, I'm not using docker. And no luck with `self.logger.error()` either, unfortunately.

**Comment by bcail** [comment]
ok, try removing your "$PATH" and $JAVA_HOME values from PATH.

**Comment by lguariento** [comment]
Great, that worked, thanks! I don't get any error now. But the webserver is not showing when I go to :8888.

**Comment by bcail** [comment]
Great. Could you please close this issue, and open a new one with the new problem?

**Comment by lguariento** [comment]
OK, will do!
